"""Solved leaf mini-board export utility.

This module writes a minimal KiCad `.kicad_pcb` snapshot for a solved leaf
subcircuit layout. The output is intentionally lightweight and text-based so it
can be generated without pcbnew.

Current scope:
- export a synthetic rectangular board outline
- export footprint positions/rotations/layers for solved components
- export simple segment/via copper from the solved local layout
- annotate inferred interface anchors as comments and gr_text markers
- keep the file human-inspectable for debugging and artifact review

This is not yet a full-fidelity KiCad board serializer. It is a pragmatic
artifact writer for the subcircuits redesign, intended to make solved leaf
layouts inspectable and versionable while later milestones add richer board
reconstruction.
"""

from __future__ import annotations

import math
import uuid
from dataclasses import dataclass
from pathlib import Path

from .types import Layer, SubCircuitLayout

KICAD_PCB_VERSION = "20250114"
KICAD_GENERATOR = "subcircuits-export"
EDGE_WIDTH_MM = 0.05
DEFAULT_SEGMENT_WIDTH_MM = 0.25
DEFAULT_TEXT_SIZE_MM = 1.0
DEFAULT_TEXT_THICKNESS_MM = 0.15


@dataclass(slots=True)
class ExportOptions:
    """Options controlling mini-board export formatting."""

    title: str = "Subcircuit Mini Board"
    company: str = "Subcircuit Export"
    comment: str = "Generated by subcircuit_board_export.py"
    edge_width_mm: float = EDGE_WIDTH_MM
    include_interface_labels: bool = True
    include_anchor_markers: bool = True
    include_notes_as_comments: bool = True
    text_size_mm: float = DEFAULT_TEXT_SIZE_MM
    text_thickness_mm: float = DEFAULT_TEXT_THICKNESS_MM


def export_subcircuit_board(
    layout: SubCircuitLayout,
    output_path: str | Path,
    options: ExportOptions | None = None,
) -> str:
    """Export a solved leaf layout as a minimal `.kicad_pcb` file.

    Args:
        layout: Solved local subcircuit layout.
        output_path: Destination `.kicad_pcb` path.
        options: Optional export formatting options.

    Returns:
        The written output path as a string.
    """
    opts = options or ExportOptions()
    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_subcircuit_board(layout, opts), encoding="utf-8")
    return str(out_path)


def render_subcircuit_board(
    layout: SubCircuitLayout,
    options: ExportOptions | None = None,
) -> str:
    """Render a solved leaf layout into KiCad PCB text."""
    opts = options or ExportOptions()
    width = max(1.0, float(layout.width))
    height = max(1.0, float(layout.height))

    lines: list[str] = []
    lines.append("(kicad_pcb")
    lines.append(f"\t(version {KICAD_PCB_VERSION})")
    lines.append('\t(generator "' + KICAD_GENERATOR + '")')
    lines.append(f'\t(generator_version "1.0")')
    lines.append(
        '\t(uuid "' + _stable_uuid(layout.subcircuit_id.instance_path, "board") + '")'
    )
    lines.append('\t(paper "A4")')
    lines.append("")
    lines.extend(_render_title_block(layout, opts))
    lines.append("")
    lines.extend(_render_layers())
    lines.append("")
    lines.extend(_render_setup())
    lines.append("")
    lines.extend(_render_board_outline(width, height, opts.edge_width_mm))
    lines.append("")

    if opts.include_notes_as_comments:
        lines.extend(_render_layout_comments(layout))
        if lines and lines[-1] != "":
            lines.append("")

    for ref in sorted(layout.components.keys()):
        lines.extend(_render_footprint(layout.components[ref]))
        lines.append("")

    for trace in layout.traces:
        lines.extend(_render_trace(trace))
    if layout.traces:
        lines.append("")

    for via in layout.vias:
        lines.extend(_render_via(via))
    if layout.vias:
        lines.append("")

    if opts.include_interface_labels or opts.include_anchor_markers:
        lines.extend(_render_interface_annotations(layout, opts))

    if lines and lines[-1] == "":
        lines.pop()

    lines.append(")")
    return "\n".join(lines) + "\n"


def _render_title_block(layout: SubCircuitLayout, opts: ExportOptions) -> list[str]:
    name = layout.subcircuit_id.sheet_name or "Subcircuit"
    instance_path = layout.subcircuit_id.instance_path or "/"
    return [
        "\t(title_block",
        f'\t\t(title "{_escape(name)}")',
        '\t\t(rev "subcircuits")',
        f'\t\t(company "{_escape(opts.company)}")',
        f'\t\t(comment 1 "{_escape(opts.title)}")',
        f'\t\t(comment 2 "{_escape(opts.comment)}")',
        f'\t\t(comment 3 "instance_path={_escape(instance_path)}")',
        "\t)",
    ]


def _render_layers() -> list[str]:
    return [
        "\t(layers",
        '\t\t(0 "F.Cu" signal)',
        '\t\t(31 "B.Cu" signal)',
        '\t\t(36 "B.SilkS" user)',
        '\t\t(37 "F.SilkS" user)',
        '\t\t(38 "B.Mask" user)',
        '\t\t(39 "F.Mask" user)',
        '\t\t(44 "Edge.Cuts" user)',
        '\t\t(45 "Margin" user)',
        '\t\t(46 "B.CrtYd" user)',
        '\t\t(47 "F.CrtYd" user)',
        '\t\t(48 "B.Fab" user)',
        '\t\t(49 "F.Fab" user)',
        "\t)",
    ]


def _render_setup() -> list[str]:
    return [
        "\t(setup",
        "\t\t(pad_to_mask_clearance 0)",
        "\t\t(allow_soldermask_bridges_in_footprints no)",
        "\t\t(grid_origin 0 0)",
        "\t)",
    ]


def _render_board_outline(
    width: float, height: float, edge_width_mm: float
) -> list[str]:
    uid_base = _stable_uuid(f"{width:.3f}x{height:.3f}", "edge")
    corners = [
        (0.0, 0.0, width, 0.0),
        (width, 0.0, width, height),
        (width, height, 0.0, height),
        (0.0, height, 0.0, 0.0),
    ]
    lines: list[str] = []
    for idx, (x1, y1, x2, y2) in enumerate(corners):
        lines.extend(
            [
                "\t(gr_line",
                f"\t\t(start {_fmt(x1)} {_fmt(y1)})",
                f"\t\t(end {_fmt(x2)} {_fmt(y2)})",
                "\t\t(stroke (width " + _fmt(edge_width_mm) + ") (type solid))",
                '\t\t(layer "Edge.Cuts")',
                f'\t\t(uuid "{_stable_uuid(uid_base, str(idx))}")',
                "\t)",
            ]
        )
    return lines


def _render_layout_comments(layout: SubCircuitLayout) -> list[str]:
    lines: list[str] = []
    lines.append(
        f'\t(comment "subcircuit={_escape(layout.subcircuit_id.sheet_name)} '
        f"instance_path={_escape(layout.subcircuit_id.instance_path)} "
        f'score={layout.score:.3f}")'
    )
    lines.append(
        f'\t(comment "bbox={layout.width:.3f}x{layout.height:.3f}mm '
        f'components={len(layout.components)} traces={len(layout.traces)} vias={len(layout.vias)}")'
    )
    return lines


def _render_footprint(component) -> list[str]:
    layer_name = _layer_name(component.layer)
    silk_layer = "B.SilkS" if component.layer == Layer.BACK else "F.SilkS"
    fab_layer = "B.Fab" if component.layer == Layer.BACK else "F.Fab"
    crtyd_layer = "B.CrtYd" if component.layer == Layer.BACK else "F.CrtYd"

    width = max(0.5, float(component.width_mm))
    height = max(0.5, float(component.height_mm))
    hw = width / 2.0
    hh = height / 2.0

    uid = _stable_uuid(component.ref, "footprint")
    ref_uid = _stable_uuid(component.ref, "ref")
    val_uid = _stable_uuid(component.ref, "val")

    lines = [
        f'\t(footprint "{_escape(component.value or component.ref)}"',
        f'\t\t(layer "{layer_name}")',
        f'\t\t(uuid "{uid}")',
        f"\t\t(at {_fmt(component.pos.x)} {_fmt(component.pos.y)} {_fmt(component.rotation)})",
        "\t\t(attr board_only exclude_from_pos_files exclude_from_bom)",
        f'\t\t(property "Reference" "{_escape(component.ref)}"',
        f"\t\t\t(at 0 {-hh - 1.5:.3f} 0)",
        f'\t\t\t(layer "{silk_layer}")',
        "\t\t\t(effects (font (size 1 1) (thickness 0.15)))",
        f'\t\t\t(uuid "{ref_uid}")',
        "\t\t)",
        f'\t\t(property "Value" "{_escape(component.value or "")}"',
        f"\t\t\t(at 0 {hh + 1.5:.3f} 0)",
        f'\t\t\t(layer "{fab_layer}")',
        "\t\t\t(effects (font (size 1 1) (thickness 0.15)))",
        f'\t\t\t(uuid "{val_uid}")',
        "\t\t)",
    ]

    lines.extend(
        _render_component_box(hw, hh, silk_layer, fab_layer, crtyd_layer, component.ref)
    )
    lines.extend(_render_component_pads(component))
    lines.append("\t)")
    return lines


def _render_component_box(
    hw: float,
    hh: float,
    silk_layer: str,
    fab_layer: str,
    crtyd_layer: str,
    ref: str,
) -> list[str]:
    lines: list[str] = []

    # Fab outline
    lines.extend(
        [
            "\t\t(fp_rect",
            f"\t\t\t(start {-hw:.3f} {-hh:.3f})",
            f"\t\t\t(end {hw:.3f} {hh:.3f})",
            "\t\t\t(stroke (width 0.1) (type solid))",
            f'\t\t\t(layer "{fab_layer}")',
            '\t\t\t(uuid "' + _stable_uuid(ref, "fab") + '")',
            "\t\t)",
        ]
    )

    # Courtyard
    lines.extend(
        [
            "\t\t(fp_rect",
            f"\t\t\t(start {-hw - 0.25:.3f} {-hh - 0.25:.3f})",
            f"\t\t\t(end {hw + 0.25:.3f} {hh + 0.25:.3f})",
            "\t\t\t(stroke (width 0.05) (type solid))",
            f'\t\t\t(layer "{crtyd_layer}")',
            '\t\t\t(uuid "' + _stable_uuid(ref, "crtyd") + '")',
            "\t\t)",
        ]
    )

    # Silk top/bottom short markers
    silk_y = hh + 0.1
    lines.extend(
        [
            "\t\t(fp_line",
            f"\t\t\t(start {-hw:.3f} {-silk_y:.3f})",
            f"\t\t\t(end {hw:.3f} {-silk_y:.3f})",
            "\t\t\t(stroke (width 0.12) (type solid))",
            f'\t\t\t(layer "{silk_layer}")',
            f'\t\t\t(uuid "{_stable_uuid(ref, "silk_top")}")',
            "\t\t)",
            "\t\t(fp_line",
            f"\t\t\t(start {-hw:.3f} {silk_y:.3f})",
            f"\t\t\t(end {hw:.3f} {silk_y:.3f})",
            "\t\t\t(stroke (width 0.12) (type solid))",
            f'\t\t\t(layer "{silk_layer}")',
            f'\t\t\t(uuid "{_stable_uuid(ref, "silk_bot")}")',
            "\t\t)",
        ]
    )
    return lines


def _render_component_pads(component) -> list[str]:
    lines: list[str] = []
    for idx, pad in enumerate(component.pads):
        local_x = pad.pos.x - component.pos.x
        local_y = pad.pos.y - component.pos.y
        pad_layer = _pad_layers(component.layer)
        pad_size = _estimate_pad_size(component, len(component.pads), idx)
        pad_type = "thru_hole" if component.is_through_hole else "smd"
        shape = "circle" if component.is_through_hole else "rect"

        lines.extend(
            [
                f'\t\t(pad "{_escape(pad.pad_id)}" {pad_type} {shape}',
                f"\t\t\t(at {_fmt(local_x)} {_fmt(local_y)} 0)",
                f"\t\t\t(size {_fmt(pad_size[0])} {_fmt(pad_size[1])})",
                f"\t\t\t(layers {pad_layer})",
                f'\t\t\t(net 0 "{_escape(pad.net)}")',
                f'\t\t\t(pinfunction "{_escape(pad.pad_id)}")',
                f'\t\t\t(pintype "passive")',
                '\t\t\t(uuid "'
                + _stable_uuid(component.ref, f"pad-{pad.pad_id}-{idx}")
                + '")',
                "\t\t)",
            ]
        )
    return lines


def _render_trace(trace) -> list[str]:
    return [
        "\t(segment",
        f"\t\t(start {_fmt(trace.start.x)} {_fmt(trace.start.y)})",
        f"\t\t(end {_fmt(trace.end.x)} {_fmt(trace.end.y)})",
        f"\t\t(width {_fmt(max(0.05, trace.width_mm or DEFAULT_SEGMENT_WIDTH_MM))})",
        f'\t\t(layer "{_layer_name(trace.layer)}")',
        f"\t\t(net 0)",
        '\t\t(uuid "'
        + _stable_uuid(
            trace.net,
            f"{trace.start.x:.3f},{trace.start.y:.3f}->{trace.end.x:.3f},{trace.end.y:.3f}",
        )
        + '")',
        "\t)",
    ]


def _render_via(via) -> list[str]:
    return [
        "\t(via",
        f"\t\t(at {_fmt(via.pos.x)} {_fmt(via.pos.y)})",
        f"\t\t(size {_fmt(max(via.size_mm, 0.3))})",
        f"\t\t(drill {_fmt(max(via.drill_mm, 0.1))})",
        '\t\t(layers "F.Cu" "B.Cu")',
        "\t\t(net 0)",
        f'\t\t(uuid "{_stable_uuid(via.net, f"via-{via.pos.x:.3f}-{via.pos.y:.3f}")}")',
        "\t)",
    ]


def _render_interface_annotations(
    layout: SubCircuitLayout,
    opts: ExportOptions,
) -> list[str]:
    lines: list[str] = []
    for idx, anchor in enumerate(layout.interface_anchors):
        layer = "F.SilkS" if anchor.layer == Layer.FRONT else "B.SilkS"
        marker_uid = _stable_uuid(anchor.port_name, f"anchor-{idx}")
        label_uid = _stable_uuid(anchor.port_name, f"label-{idx}")

        if opts.include_anchor_markers:
            r = 0.6
            lines.extend(
                [
                    "\t(gr_circle",
                    f"\t\t(center {_fmt(anchor.pos.x)} {_fmt(anchor.pos.y)})",
                    f"\t\t(end {_fmt(anchor.pos.x + r)} {_fmt(anchor.pos.y)})",
                    "\t\t(stroke (width 0.12) (type solid))",
                    "\t\t(fill (type none))",
                    f'\t\t(layer "{layer}")',
                    f'\t\t(uuid "{marker_uid}")',
                    "\t)",
                ]
            )

        if opts.include_interface_labels:
            label = anchor.port_name
            if anchor.pad_ref:
                label = f"{anchor.port_name} ({anchor.pad_ref[0]}:{anchor.pad_ref[1]})"
            lines.extend(
                [
                    f'\t(gr_text "{_escape(label)}"',
                    f"\t\t(at {_fmt(anchor.pos.x + 1.0)} {_fmt(anchor.pos.y - 1.0)} 0)",
                    f'\t\t(layer "{layer}")',
                    "\t\t(effects",
                    f"\t\t\t(font (size {_fmt(opts.text_size_mm)} {_fmt(opts.text_size_mm)}) "
                    f"(thickness {_fmt(opts.text_thickness_mm)}))",
                    "\t\t)",
                    f'\t\t(uuid "{label_uid}")',
                    "\t)",
                ]
            )
    return lines


def _layer_name(layer: Layer) -> str:
    return "B.Cu" if layer == Layer.BACK else "F.Cu"


def _pad_layers(layer: Layer) -> str:
    if layer == Layer.BACK:
        return '"B.Cu" "B.Mask" "B.Paste"'
    return '"F.Cu" "F.Mask" "F.Paste"'


def _estimate_pad_size(
    component, pad_count: int, pad_index: int
) -> tuple[float, float]:
    """Estimate a reasonable pad size for debug/export purposes."""
    base_w = max(
        0.5, min(2.0, component.width_mm / max(2.0, math.sqrt(max(1, pad_count))))
    )
    base_h = max(
        0.5, min(2.0, component.height_mm / max(2.0, math.sqrt(max(1, pad_count))))
    )
    if component.is_through_hole:
        size = max(1.2, min(2.5, max(base_w, base_h)))
        return (size, size)
    return (base_w, base_h)


def _stable_uuid(*parts: str) -> str:
    seed = "::".join(parts)
    return str(uuid.uuid5(uuid.NAMESPACE_URL, seed))


def _fmt(value: float) -> str:
    return f"{float(value):.3f}".rstrip("0").rstrip(".")


def _escape(text: str) -> str:
    return (text or "").replace("\\", "\\\\").replace('"', '\\"')


__all__ = [
    "ExportOptions",
    "export_subcircuit_board",
    "render_subcircuit_board",
]
